'use client';

import { useState } from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { CssBaseline, ThemeProvider } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const [isDark, setIsDark] = useState(false);

	const toggleDark = () => {
		setIsDark(!isDark);
	};

	return (
		<html lang='en'>
			<ThemeProvider theme={isDark ? 'dark' : 'light'}>
				<CssBaseline /> // This is the MUI component that sets the theme
				<body className={inter.className}>{children}</body>
			</ThemeProvider>
		</html>
	);
}
